hi am updating aline
add this line in othefr branch sector and more to go....
am adding a new line 
hi guys gt commands are very important...
have to go through the classes regularly without fail....
have to practice it on daily basis
am back withh other line added
